/**
 * Compile strategy_seeds.json → src/knowledge/bookIngestRules.ts
 * Run: node scripts/compile_ingest_rules.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(__dirname, "..");
const seedsPath = path.join(REPO, "src/knowledge/catalog/ingested/strategy_seeds.json");
const manifestPath = path.join(REPO, "src/knowledge/catalog/ingested/manifest.json");
const outPath = path.join(REPO, "src/knowledge/bookIngestRules.ts");

const seeds = JSON.parse(fs.readFileSync(seedsPath, "utf8"));
const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));

function esc(s) {
  return String(s)
    .replace(/\\/g, "\\\\")
    .replace(/'/g, "\\'")
    .replace(/\r?\n/g, " ");
}

const lines = [];
lines.push("/**");
lines.push(" * AUTO-GENERATED by scripts/compile_ingest_rules.mjs — do not hand-edit.");
lines.push(" * Source: src/knowledge/catalog/ingested/strategy_seeds.json");
lines.push(` * Ingested: ${manifest.ingestedAt}`);
lines.push(
  ` * Books OK: ${manifest.booksOk}/${manifest.pdfCount} | entries: ${manifest.entryCount}`
);
lines.push(" * Educational decision support only — not investment advice.");
lines.push(" */");
lines.push("");
lines.push('import type { StrategyRule } from "./types";');
lines.push("");
lines.push("export const BOOK_INGEST_META = {");
lines.push('  version: "1.0.0",');
lines.push(`  ingestedAt: ${JSON.stringify(manifest.ingestedAt)},`);
lines.push(`  booksOk: ${manifest.booksOk},`);
lines.push(`  pdfCount: ${manifest.pdfCount},`);
lines.push(`  entryCount: ${manifest.entryCount},`);
lines.push(`  seedCount: ${seeds.length},`);
lines.push("} as const;");
lines.push("");
lines.push("export const BOOK_INGEST_RULES: StrategyRule[] = [");

for (const s of seeds) {
  const pri = Math.max(0.3, Math.min(0.93, Number((s.priority * 0.97).toFixed(3))));
  const shortDelta = s.shortDeltaTarget == null ? "null" : String(s.shortDeltaTarget);
  const bookSource = String(s.bookSource).replace(/ \[.*\]$/, "");

  lines.push("  {");
  lines.push(`    id: '${esc(s.id)}',`);
  lines.push(`    strategyId: '${esc(s.strategyId)}',`);
  lines.push(`    name: '${esc(s.name)}',`);
  lines.push(`    thesis: '${esc(s.thesis)}',`);
  lines.push(`    portfolioRole: '${esc(s.portfolioRole)}',`);
  lines.push(`    riskProfile: '${esc(s.riskProfile)}',`);
  lines.push(`    approval: '${esc(s.approval)}',`);
  lines.push(`    ivConditions: ${JSON.stringify(s.ivConditions)},`);
  lines.push(`    trends: ${JSON.stringify(s.trends)},`);
  lines.push(`    eventStance: '${esc(s.eventStance)}',`);
  lines.push(`    minLiquidity: '${esc(s.minLiquidity)}',`);
  lines.push(`    newsBias: '${esc(s.newsBias)}',`);
  lines.push("    entryRules: [");
  for (const r of s.entryRules) lines.push(`      '${esc(r)}',`);
  lines.push("    ],");
  lines.push(`    exitRules: ${JSON.stringify(s.exitRules)},`);
  lines.push(`    shortDeltaTarget: ${shortDelta},`);
  lines.push(`    dteMin: ${s.dteMin},`);
  lines.push(`    dteMax: ${s.dteMax},`);
  lines.push(`    priority: ${pri},`);
  lines.push(`    growthPrimary: ${!!s.growthPrimary},`);
  lines.push(`    bookSource: '${esc(bookSource)}',`);
  lines.push(`    structure: '${esc(s.structure)}',`);
  lines.push("    notes: [");
  for (const n of s.notes) lines.push(`      '${esc(n)}',`);
  lines.push(`      'hitWeight=${s.hitWeight || 0}',`);
  lines.push("    ],");
  lines.push("  },");
}

lines.push("];");
lines.push("");

fs.writeFileSync(outPath, lines.join("\n"), "utf8");
console.log(`Wrote ${outPath} (${seeds.length} rules)`);
