/**
 * Extra strategy rules distilled from Michael's option-book library
 * (Documents/Claude/Projects/option trader + Master Trader books).
 * Structured for the selector — not free-form prose.
 */

import type { StrategyRule } from "./types";

export const BOOK_EXTRA_RULES: StrategyRule[] = [
  {
    id: "put_credit_iv_crush",
    strategyId: "bull_put_credit",
    name: "Post-Event IV Crush Put Credit (Book)",
    thesis: "moderately_bullish",
    portfolioRole: "income_engine",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["elevated"],
    trends: ["up", "sideways"],
    eventStance: "prefer_clear",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "Prefer AFTER earnings/event when IV rank still elevated but event risk passed",
      "Short put delta 0.20–0.30, 21–45 DTE",
      "Defined width; never naked in companion mode",
      "Target 50% of max credit to close",
    ],
    exitRules: ["profit_50pct_max", "dte_21_close_or_roll", "stop_2x_credit"],
    shortDeltaTarget: 0.25,
    dteMin: 21,
    dteMax: 45,
    priority: 0.86,
    growthPrimary: true,
    bookSource:
      "Option Trading Pricing & Volatility Strategies (2010); The Option Trader's Guide to Probability, Volatility & Timing (2002)",
    structure: "Bull put credit after event — sell elevated IV with defined risk",
    notes: ["Classic vol-selling workflow from probability/vol books"],
  },
  {
    id: "conservative_csp_quality",
    strategyId: "cash_secured_put",
    name: "Conservative Investor CSP (Book)",
    thesis: "moderately_bullish",
    portfolioRole: "income_engine",
    riskProfile: "substantial_downside_capped_upside",
    approval: "level2_basic",
    ivConditions: ["elevated", "neutral"],
    trends: ["up", "sideways"],
    eventStance: "avoid_earnings",
    minLiquidity: "tight",
    newsBias: "any",
    entryRules: [
      "Only names you are willing to own for 100 shares × contracts",
      "Strike at support / technical demand, not random OTM",
      "Prefer liquid large-caps & ETFs (SPY/QQQ/AAPL-class)",
      "Cash fully reserved — no margin fantasy in Robinhood companion mode",
    ],
    exitRules: ["profit_50pct_max", "assignment_then_cc", "dte_21_close_or_roll"],
    shortDeltaTarget: 0.2,
    dteMin: 30,
    dteMax: 45,
    priority: 0.92,
    growthPrimary: true,
    bookSource: "Options Trading for the Conservative Investor (2010); Equity Options Strategy Guide (2010)",
    structure: "Cash-secured put as stock-acquisition / income hybrid",
    notes: ["Aligns with portfolio core building: assignment → covered call wheel"],
  },
  {
    id: "spread_book_vertical_debit",
    strategyId: "bull_call_debit",
    name: "Vertical Debit — Defined Directional (Book)",
    thesis: "bullish",
    portfolioRole: "growth_tactical",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["low", "neutral"],
    trends: ["up"],
    eventStance: "prefer_clear",
    minLiquidity: "normal",
    newsBias: "positive",
    entryRules: [
      "Buy premium only when IV is not elevated",
      "Width chosen so debit ≤ 50% of width (positive reward skew)",
      "NCI TA master BULL or FIRE BUY preferred as timing overlay",
      "Risk = full debit; size with 1% rule",
    ],
    exitRules: ["profit_50pct_max", "stop_1x_debit", "manual_review"],
    shortDeltaTarget: null,
    dteMin: 21,
    dteMax: 60,
    priority: 0.72,
    growthPrimary: false,
    bookSource: "Option Spread Strategies (2009); The Complete Book of Options Spreads (2014)",
    structure: "Bull call vertical debit",
    notes: ["From spread handbooks: prefer debit when directional conviction + cheap IV"],
  },
  {
    id: "iron_condor_elevated_iv_book",
    strategyId: "iron_condor",
    name: "Iron Condor — Elevated IV Range (Book)",
    thesis: "range",
    portfolioRole: "income_engine",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["elevated"],
    trends: ["sideways"],
    eventStance: "avoid_earnings",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "IV rank high — sell wings outside expected move",
      "NCI master FLAT or weak trend preferred",
      "Avoid when SuperBias FIRE directional is screaming",
      "Manage at 50% profit; close by 21 DTE",
    ],
    exitRules: ["profit_50pct_max", "dte_21_close_or_roll", "stop_2x_credit"],
    shortDeltaTarget: 0.16,
    dteMin: 25,
    dteMax: 45,
    priority: 0.82,
    growthPrimary: false,
    bookSource: "Options Made Easy (2005); Option Strategies Quick Guide (2010)",
    structure: "Short put spread + short call spread",
    notes: ["Range income when chart bias is flat"],
  },
  {
    id: "protective_put_portfolio",
    strategyId: "long_put",
    name: "Protective Put on Core Portfolio (Book)",
    thesis: "bearish",
    portfolioRole: "hedge",
    riskProfile: "defined",
    approval: "level2_basic",
    ivConditions: ["low", "neutral"],
    trends: ["down", "sideways"],
    eventStance: "ok_through_events",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "Hedge portfolio core when NCI master turns BEAR with gates pass",
      "Size puts to cover delta of shares/ETF held",
      "Cost is insurance — do not size as speculation",
    ],
    exitRules: ["manual_review", "profit_50pct_max"],
    shortDeltaTarget: null,
    dteMin: 30,
    dteMax: 90,
    priority: 0.55,
    growthPrimary: false,
    bookSource: "Put Option Strategies for Smarter Trading (2010); Visual Guide to Options (2013)",
    structure: "Long put as portfolio insurance",
    notes: ["Pairs with portfolioCore growth path"],
  },
];
