/**
 * Extra strategy rules distilled from Michael's option-book library
 * (Documents/Claude/Projects/option trader + Master Trader books).
 * Structured for the selector — not free-form prose.
 */

import type { StrategyRule } from "./types";

export const BOOK_EXTRA_RULES: StrategyRule[] = [
  {
    id: "put_credit_iv_crush",
    strategyId: "bull_put_credit",
    name: "Post-Event IV Crush Put Credit (Book)",
    thesis: "moderately_bullish",
    portfolioRole: "income_engine",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["elevated"],
    trends: ["up", "sideways"],
    eventStance: "prefer_clear",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "Prefer AFTER earnings/event when IV rank still elevated but event risk passed",
      "Short put delta 0.20–0.30, 21–45 DTE",
      "Defined width; never naked in companion mode",
      "Target 50% of max credit to close",
    ],
    exitRules: ["profit_50pct_max", "dte_21_close_or_roll", "stop_2x_credit"],
    shortDeltaTarget: 0.25,
    dteMin: 21,
    dteMax: 45,
    priority: 0.86,
    growthPrimary: true,
    bookSource:
      "Option Trading Pricing & Volatility Strategies (2010); The Option Trader's Guide to Probability, Volatility & Timing (2002)",
    structure: "Bull put credit after event — sell elevated IV with defined risk",
    notes: ["Classic vol-selling workflow from probability/vol books"],
  },
  {
    id: "conservative_csp_quality",
    strategyId: "cash_secured_put",
    name: "Conservative Investor CSP (Book)",
    thesis: "moderately_bullish",
    portfolioRole: "income_engine",
    riskProfile: "substantial_downside_capped_upside",
    approval: "level2_basic",
    ivConditions: ["elevated", "neutral"],
    trends: ["up", "sideways"],
    eventStance: "avoid_earnings",
    minLiquidity: "tight",
    newsBias: "any",
    entryRules: [
      "Only names you are willing to own for 100 shares × contracts",
      "Strike at support / technical demand, not random OTM",
      "Prefer liquid large-caps & ETFs (SPY/QQQ/AAPL-class)",
      "Cash fully reserved — no margin fantasy in Robinhood companion mode",
    ],
    exitRules: ["profit_50pct_max", "assignment_then_cc", "dte_21_close_or_roll"],
    shortDeltaTarget: 0.2,
    dteMin: 30,
    dteMax: 45,
    priority: 0.92,
    growthPrimary: true,
    bookSource: "Options Trading for the Conservative Investor (2010); Equity Options Strategy Guide (2010)",
    structure: "Cash-secured put as stock-acquisition / income hybrid",
    notes: ["Aligns with portfolio core building: assignment → covered call wheel"],
  },
  {
    id: "spread_book_vertical_debit",
    strategyId: "bull_call_debit",
    name: "Vertical Debit — Defined Directional (Book)",
    thesis: "bullish",
    portfolioRole: "growth_tactical",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["low", "neutral"],
    trends: ["up"],
    eventStance: "prefer_clear",
    minLiquidity: "normal",
    newsBias: "positive",
    entryRules: [
      "Buy premium only when IV is not elevated",
      "Width chosen so debit ≤ 50% of width (positive reward skew)",
      "NCI TA master BULL or FIRE BUY preferred as timing overlay",
      "Risk = full debit; size with 1% rule",
    ],
    exitRules: ["profit_50pct_max", "stop_1x_debit", "manual_review"],
    shortDeltaTarget: null,
    dteMin: 21,
    dteMax: 60,
    priority: 0.72,
    growthPrimary: false,
    bookSource: "Option Spread Strategies (2009); The Complete Book of Options Spreads (2014)",
    structure: "Bull call vertical debit",
    notes: ["From spread handbooks: prefer debit when directional conviction + cheap IV"],
  },
  {
    id: "iron_condor_elevated_iv_book",
    strategyId: "iron_condor",
    name: "Iron Condor — Elevated IV Range (Book)",
    thesis: "range",
    portfolioRole: "income_engine",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["elevated"],
    trends: ["sideways"],
    eventStance: "avoid_earnings",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "IV rank high — sell wings outside expected move",
      "NCI master FLAT or weak trend preferred",
      "Avoid when SuperBias FIRE directional is screaming",
      "Manage at 50% profit; close by 21 DTE",
    ],
    exitRules: ["profit_50pct_max", "dte_21_close_or_roll", "stop_2x_credit"],
    shortDeltaTarget: 0.16,
    dteMin: 25,
    dteMax: 45,
    priority: 0.82,
    growthPrimary: false,
    bookSource: "Options Made Easy (2005); Option Strategies Quick Guide (2010)",
    structure: "Short put spread + short call spread",
    notes: ["Range income when chart bias is flat"],
  },
  {
    id: "protective_put_portfolio",
    strategyId: "long_put",
    name: "Protective Put on Core Portfolio (Book)",
    thesis: "bearish",
    portfolioRole: "hedge",
    riskProfile: "defined",
    approval: "level2_basic",
    ivConditions: ["low", "neutral"],
    trends: ["down", "sideways"],
    eventStance: "ok_through_events",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "Hedge portfolio core when NCI master turns BEAR with gates pass",
      "Size puts to cover delta of shares/ETF held",
      "Cost is insurance — do not size as speculation",
    ],
    exitRules: ["manual_review", "profit_50pct_max"],
    shortDeltaTarget: null,
    dteMin: 30,
    dteMax: 90,
    priority: 0.55,
    growthPrimary: false,
    bookSource: "Put Option Strategies for Smarter Trading (2010); Visual Guide to Options (2013)",
    structure: "Long put as portfolio insurance",
    notes: ["Pairs with portfolioCore growth path"],
  },

  // --- The Steadiest Option Trader (Henry Moldavskiy, 2023) — personal reference ---
  {
    id: "steadiest_wheel_csp",
    strategyId: "cash_secured_put",
    name: "Steadiest — Wheel CSP (Quality + Delta Band)",
    thesis: "moderately_bullish",
    portfolioRole: "income_engine",
    riskProfile: "substantial_downside_capped_upside",
    approval: "level2_basic",
    ivConditions: ["elevated", "neutral"],
    trends: ["up", "sideways"],
    eventStance: "avoid_earnings",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "Only stocks you would not mind owning (wheel step 1)",
      "Prefer quality large-caps with strong free-cash-flow yield (put-seller stock filter from book)",
      "Short put delta ~0.20–0.30 (book ideal); avoid <0.20 (thin premium) and >0.40 (near coin-flip assignment)",
      "Strike below spot (OTM); cash fully reserved for assignment",
      "Avoid earnings / binary events inside the short DTE",
      "Casino mindset: sell OTM premium with a written plan — not lottery tickets",
    ],
    exitRules: ["profit_50pct_max", "assignment_then_cc", "dte_21_close_or_roll"],
    shortDeltaTarget: 0.28,
    dteMin: 21,
    dteMax: 45,
    priority: 0.93,
    growthPrimary: true,
    bookSource:
      "Henry Moldavskiy — The Steadiest Option Trader (2023), Ch.8–9 put selling & wheel (personal reference)",
    structure: "Cash-secured put → assignment → covered call wheel",
    notes: [
      "Book marketing ROI claims are not guarantees; size under empire risk budget",
      "Assignment is acceptable if willing to own; then sell covered calls",
      "CSP cash lock usually blocks seed ladder — prefer defined credits / Money Press at micro equity",
    ],
  },
  {
    id: "steadiest_wheel_cc",
    strategyId: "covered_call",
    name: "Steadiest — Wheel Covered Call Exit",
    thesis: "neutral",
    portfolioRole: "campaign",
    riskProfile: "substantial_downside_capped_upside",
    approval: "level2_basic",
    ivConditions: ["elevated", "neutral"],
    trends: ["up", "sideways", "down"],
    eventStance: "avoid_ex_div",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "Own 100 shares per short call (wheel step after CSP assignment)",
      "Sell call OTM — income cushion, not full downside hedge",
      "Continue only on names still in the long-term own list",
    ],
    exitRules: ["profit_50pct_max", "dte_21_close_or_roll", "manual_review"],
    shortDeltaTarget: 0.3,
    dteMin: 21,
    dteMax: 45,
    priority: 0.89,
    growthPrimary: true,
    bookSource:
      "Henry Moldavskiy — The Steadiest Option Trader (2023), Ch.4 & Ch.9 covered calls / wheel (personal reference)",
    structure: "Long stock + short call (wheel cashflow exit)",
    notes: ["Second leg of the cashflow machine after assignment"],
  },
  {
    id: "steadiest_put_credit",
    strategyId: "bull_put_credit",
    name: "Steadiest — Put Credit Spread (Defined Seller)",
    thesis: "moderately_bullish",
    portfolioRole: "income_engine",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["elevated", "neutral"],
    trends: ["up", "sideways"],
    eventStance: "avoid_earnings",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "Sell higher put + buy lower put same expiry (bull put credit)",
      "Max profit = net credit; max loss = width − credit",
      "Prefer elevated IV / theta working for the seller",
      "Defined-risk alternative to CSP when capital is tight or Level 3 available",
      "Close Friday morning if price is between strikes near expiry (pin-risk pro tip)",
    ],
    exitRules: ["profit_50pct_max", "dte_21_close_or_roll", "stop_2x_credit", "friday_roll_or_close"],
    shortDeltaTarget: 0.3,
    dteMin: 21,
    dteMax: 45,
    priority: 0.9,
    growthPrimary: true,
    bookSource:
      "Henry Moldavskiy — The Steadiest Option Trader (2023), Ch.12 put credit spreads + pin-risk tip (personal reference)",
    structure: "Short higher put + long lower put, same expiry",
    notes: [
      "Seed-friendly vs CSP when width is small",
      "Pin risk: assignment complexity if short put settles ITM near long wing",
    ],
  },
  {
    id: "steadiest_call_credit",
    strategyId: "bear_call_credit",
    name: "Steadiest — Call Credit Spread (Resistance / Neutral)",
    thesis: "moderately_bearish",
    portfolioRole: "income_engine",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["elevated", "neutral"],
    trends: ["down", "sideways"],
    eventStance: "prefer_clear",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "Sell lower call + buy higher call same expiry (bear call credit)",
      "Use near technical resistance, consolidation range tops, or overbought pullbacks",
      "Max profit = net credit; max loss = width − credit",
      "Prefer when expecting price to stay below short strike through expiry",
      "Pre-define exit and position size before entry",
    ],
    exitRules: ["profit_50pct_max", "dte_21_close_or_roll", "stop_2x_credit", "friday_roll_or_close"],
    shortDeltaTarget: 0.3,
    dteMin: 14,
    dteMax: 45,
    priority: 0.86,
    growthPrimary: true,
    bookSource:
      "Henry Moldavskiy — The Steadiest Option Trader (2023), Ch.11 call credit spreads (personal reference)",
    structure: "Short lower call + long higher call, same expiry",
    notes: ["Book setups: resistance, overbought, index neutral/bear, consolidation"],
  },
  {
    id: "steadiest_iron_condor",
    strategyId: "iron_condor",
    name: "Steadiest — Iron Condor Range Seller",
    thesis: "range",
    portfolioRole: "income_engine",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["elevated"],
    trends: ["sideways"],
    eventStance: "avoid_earnings",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "OTM put credit + OTM call credit same expiry (condor profit zone)",
      "Elevated IV preferred; range-bound thesis required",
      "Shorter DTE for faster theta but tighter management",
      "Roll or close if price approaches short wings; do not hope through a breakout",
      "Show PoP and max loss together before sizing",
    ],
    exitRules: ["profit_50pct_max", "dte_21_close_or_roll", "stop_2x_credit"],
    shortDeltaTarget: 0.16,
    dteMin: 21,
    dteMax: 40,
    priority: 0.81,
    growthPrimary: false,
    bookSource:
      "Henry Moldavskiy — The Steadiest Option Trader (2023), Ch.13 iron condors (personal reference)",
    structure: "Short put spread + short call spread",
    notes: ["Income when market is expected to stay in a band; manage proactively"],
  },
];
