/**
 * Query helpers over the ingested option-book knowledge catalog.
 * Catalog is generated by scripts/ingest_option_pdfs.py.
 */

import catalogJson from "./catalog/ingested/ota_knowledge_catalog.json";
import { BOOK_INGEST_META } from "./bookIngestRules";

export interface CatalogSnippet {
  snippet: string;
  source: string;
  page: number | null;
  keyword: string;
}

export interface CatalogQueryResult {
  category: string;
  subsection: string;
  hits: CatalogSnippet[];
}

type CatalogShape = Record<string, unknown>;

const catalog = catalogJson as CatalogShape;

export function getIngestMeta() {
  return BOOK_INGEST_META;
}

/** List top-level categories that have subsections. */
export function listCatalogCategories(): string[] {
  return Object.keys(catalog).filter((k) => k !== "Source References" && typeof catalog[k] === "object");
}

/**
 * Simple keyword search across ingested snippets.
 * Returns up to `limit` subsection hits with matching snippet text.
 */
export function searchCatalog(query: string, limit = 12): CatalogQueryResult[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const out: CatalogQueryResult[] = [];

  for (const category of listCatalogCategories()) {
    const block = catalog[category];
    if (!block || typeof block !== "object") continue;
    for (const [subsection, entries] of Object.entries(block as Record<string, unknown>)) {
      if (!Array.isArray(entries)) continue;
      const hits: CatalogSnippet[] = [];
      for (const e of entries) {
        if (!e || typeof e !== "object") continue;
        const row = e as Record<string, unknown>;
        const snip = String(row.snippet ?? "");
        const kw = String(row.keyword ?? "");
        if (snip.toLowerCase().includes(q) || kw.toLowerCase().includes(q) || subsection.toLowerCase().includes(q)) {
          hits.push({
            snippet: snip,
            source: String(row.source ?? ""),
            page: typeof row.page === "number" ? row.page : null,
            keyword: kw,
          });
        }
      }
      if (hits.length) {
        out.push({ category, subsection, hits: hits.slice(0, 4) });
      }
      if (out.length >= limit) return out;
    }
  }
  return out;
}

/** Cite book sources that back a strategyId (from Source References + rules). */
export function listIngestedSources(): { title: string; path: string; entries: number }[] {
  const refs = catalog["Source References"];
  if (!Array.isArray(refs)) return [];
  return refs
    .filter((r) => r && typeof r === "object")
    .map((r) => {
      const row = r as Record<string, unknown>;
      return {
        title: String(row.title ?? ""),
        path: String(row.path ?? ""),
        entries: Number(row.entries ?? 0),
      };
    })
    .filter((r) => r.entries > 0)
    .sort((a, b) => b.entries - a.entries);
}
