/**
 * Personal Robinhood history lessons (generated by python/ota/rh_history_learn.py).
 * Soft coach for the brain — never auto-trades.
 */

import lessonsJson from "@/knowledge/catalog/ingested/rh_history_lessons.json";

export interface RhSymbolStat {
  symbol: string;
  n: number;
  win_rate: number;
  pnl: number;
  avg_pnl: number;
}

export interface RhHistoryLessons {
  generated_at?: string;
  n_matched_trades?: number;
  win_rate?: number;
  total_pnl?: number;
  avg_win?: number;
  avg_loss?: number;
  profit_factor?: number;
  by_side?: Record<string, { n: number; win_rate: number; pnl: number }>;
  patterns?: string[];
  build_on_wins?: string[];
  how_could_do_better?: string[];
  worst_symbols?: RhSymbolStat[];
  best_symbols?: RhSymbolStat[];
  assignment_count?: number;
  expiration_count?: number;
  source_path?: string;
}

export const RH_HISTORY_LESSONS: RhHistoryLessons =
  (lessonsJson as RhHistoryLessons) ?? {};

export function worstSymbolSet(): Set<string> {
  return new Set(
    (RH_HISTORY_LESSONS.worst_symbols ?? []).slice(0, 8).map((s) => s.symbol.toUpperCase())
  );
}

export function bestSymbolSet(): Set<string> {
  return new Set(
    (RH_HISTORY_LESSONS.best_symbols ?? []).slice(0, 8).map((s) => s.symbol.toUpperCase())
  );
}

/** Soft score adjustment when recommending on a ticker that appears in personal history. */
export function rhHistoryScoreAdjust(
  symbol: string,
  strategyId: string
): { delta: number; reasons: string[] } {
  const sym = symbol.toUpperCase().replace(/[^A-Z0-9]/g, "");
  const reasons: string[] = [];
  let delta = 0;
  const worst = RH_HISTORY_LESSONS.worst_symbols ?? [];
  const best = RH_HISTORY_LESSONS.best_symbols ?? [];
  const w = worst.find((x) => x.symbol.toUpperCase() === sym);
  const b = best.find((x) => x.symbol.toUpperCase() === sym);

  if (w && w.pnl < 0 && w.n >= 2) {
    delta -= 0.12;
    reasons.push(
      `Your RH history: ${sym} is a weak ticker (pnl $${w.pnl.toFixed(0)} on ${w.n} opts, wr ${(w.win_rate * 100).toFixed(0)}%) — size down or skip`
    );
  }
  if (b && b.pnl > 0 && b.n >= 3) {
    delta += 0.06;
    reasons.push(
      `Your RH history: ${sym} has paid (pnl $${b.pnl.toFixed(0)} on ${b.n}, wr ${(b.win_rate * 100).toFixed(0)}%) — build on process, still 1–2% risk`
    );
  }

  const longStats = RH_HISTORY_LESSONS.by_side?.long_option;
  const shortStats = RH_HISTORY_LESSONS.by_side?.short_option;
  const sid = strategyId.toLowerCase();
  const isLongDebit =
    sid.includes("long_") ||
    sid === "bull_call" ||
    sid === "bear_put" ||
    (sid.includes("call") && !sid.includes("credit") && !sid.includes("covered"));
  const isShortCredit =
    sid.includes("credit") ||
    sid.includes("csp") ||
    sid.includes("cash_secured") ||
    sid.includes("iron_condor") ||
    sid.includes("covered_call");

  if (longStats && longStats.win_rate < 0.35 && longStats.pnl < 0 && isLongDebit) {
    delta -= 0.1;
    reasons.push(
      `Your RH history: long options wr ${(longStats.win_rate * 100).toFixed(0)}% / pnl $${longStats.pnl.toFixed(0)} — prefer defined-risk debit spreads + time stops`
    );
  }
  if (shortStats && shortStats.win_rate >= 0.5 && shortStats.pnl > 0 && isShortCredit) {
    delta += 0.05;
    reasons.push(
      `Your RH history: short premium edge (wr ${(shortStats.win_rate * 100).toFixed(0)}%, pnl $${shortStats.pnl.toFixed(0)}) — keep defined-risk credits`
    );
  }
  if ((RH_HISTORY_LESSONS.assignment_count ?? 0) >= 20 && isShortCredit && !sid.includes("spread") && !sid.includes("condor") && sid.includes("cash_secured") === false) {
    // mild note on naked-ish shorts
    if (sid.includes("short") || sid === "naked") {
      delta -= 0.05;
      reasons.push("Your RH history: many assignments — avoid naked shorts; use spreads");
    }
  }

  return { delta, reasons };
}

export function rhCoachLinesForSymbol(symbol: string): string[] {
  const sym = symbol.toUpperCase();
  const lines: string[] = [];
  const L = RH_HISTORY_LESSONS;
  if (!L.n_matched_trades) {
    lines.push("No RH history lessons loaded — run python -m ota.rh_history_learn");
    return lines;
  }
  lines.push(
    `Personal RH sample: ${L.n_matched_trades} matched option trades · wr ${((L.win_rate ?? 0) * 100).toFixed(0)}% · P/L $${L.total_pnl ?? 0}`
  );
  const w = (L.worst_symbols ?? []).find((x) => x.symbol === sym);
  const b = (L.best_symbols ?? []).find((x) => x.symbol === sym);
  if (w) lines.push(`On ${sym}: historically weak ($${w.pnl} / ${w.n} trades)`);
  if (b) lines.push(`On ${sym}: historically paid ($${b.pnl} / ${b.n} trades)`);
  for (const p of (L.how_could_do_better ?? []).slice(0, 3)) lines.push(p);
  return lines;
}
