/**
 * Anthony J. Saliba — Option Spread Strategies (Bloomberg Press, 2009)
 * Trading Up, Down, and Sideways Markets
 *
 * Structured distillations only (entry/exit/regime). No copyrighted prose.
 * Feeds STRATEGY_RULES + Library UI + OTA catalog tags.
 *
 * Primary local PDF (user machine):
 *   E:\newdump\Saliba A. Option Spread Strategies. Trading Up, Down, and Sideways Markets 2009\...
 * Alternate:
 *   L:\newdump\Saliba A. Option Spread Strategies...
 */

import type { StrategyRule } from "./types";

export const SALIBA_META = {
  id: "saliba_option_spread_strategies_2009",
  title: "Option Spread Strategies: Trading Up, Down, and Sideways Markets",
  authors: "Anthony J. Saliba with Joseph C. Corona and Karen E. Johnson",
  year: 2009,
  isbn: "978-1-57660-260-7",
  pages: 282,
  publisher: "Bloomberg Press",
  paths: [
    "E:\\newdump\\Saliba A. Option Spread Strategies. Trading Up, Down, and Sideways Markets 2009\\Saliba A. Option Spread Strategies. Trading Up, Down, and Sideways Markets 2009.pdf",
    "L:\\newdump\\Saliba A. Option Spread Strategies. Trading Up, Down, and Sideways Markets 2009\\Saliba A. Option Spread Strategies. Trading Up, Down, and Sideways Markets 2009.pdf",
  ],
  snippet: "src/knowledge/catalog/snippets/option_spread_strategies_2009.txt",
  chapters: [
    { n: 1, title: "The Covered-Write", pages: "2–27", empire: "managed_income" as const },
    { n: 2, title: "Verticals", pages: "28–63", empire: "primary_defined" as const },
    { n: 3, title: "Collars and Reverse-Collars", pages: "64–93", empire: "hedge" as const },
    { n: 4, title: "Straddles and Strangles", pages: "94–125", empire: "vol_event" as const },
    { n: 5, title: "Butterflies and Condors", pages: "126–155", empire: "range" as const },
    { n: 6, title: "Calendar Spreads", pages: "156–189", empire: "time_structure" as const },
    { n: 7, title: "Ratio Spreads", pages: "190–221", empire: "reject_seed" as const },
    { n: 8, title: "Backspreads", pages: "222–248", empire: "reject_seed" as const },
  ],
} as const;

/**
 * Regime → preferred structures (Saliba thesis: match structure to forecast).
 * Used by UI + explain layer; selector still scores StrategyRule fields.
 */
export const SALIBA_REGIME_MATRIX = [
  {
    regime: "up" as const,
    label: "Bullish / up",
    prefer: [
      "bull_call_debit",
      "bull_put_credit",
      "covered_call",
      "money_press_put_diagonal",
    ],
    avoid: ["bear_call_credit", "bear_put_debit", "iron_condor"],
    note: "Ch.1–2: covered-write & bull verticals; debit when IV not punitive, credit when selling premium fits.",
  },
  {
    regime: "down" as const,
    label: "Bearish / down",
    prefer: ["bear_put_debit", "bear_call_credit", "long_put"],
    avoid: ["bull_call_debit", "bull_put_credit", "covered_call"],
    note: "Ch.2–3: bear verticals; collars when long stock must be retained.",
  },
  {
    regime: "sideways" as const,
    label: "Sideways / range",
    prefer: ["iron_condor", "call_butterfly", "put_butterfly", "iron_butterfly"],
    avoid: ["long_straddle", "long_strangle"],
    note: "Ch.5: butterflies & condors need S/R + mean-reversion + time-in-range for DTE.",
  },
  {
    regime: "large_move" as const,
    label: "Large move / vol expansion",
    prefer: ["long_straddle", "long_strangle"],
    avoid: ["iron_condor", "covered_call"],
    note: "Ch.4: long straddle/strangle when expecting a big move; watch IV crush after events.",
  },
] as const;

export const SALIBA_HYGIENE = [
  "Prefer multi-leg (complex) orders — avoid legging risk (book + CBOE disclosures).",
  "Know max profit and max loss before entry; wings define risk on verticals/butterflies/condors.",
  "Match structure to forecast: up / down / sideways — wrong structure = wrong P&L shape.",
  "High IV: prefer verticals over naked long options for directional views (Ch.2).",
  "Covered-write is NOT a cash machine — synthetic short-put risk; manage ruthlessly (Ch.1).",
  "Range structures need support, resistance, mean-reversion area, and expected time-in-range (Ch.5).",
  "Term structure of IV gates calendars / time spreads (Ch.6).",
  "Never close one side of a combination and leave the other naked without a new risk budget.",
  "Examples omit commissions — still size to empire net risk after fees.",
  "Educational companion only — no auto-trade; human fills on Robinhood.",
] as const;

export const SALIBA_REJECT_SEED = [
  "Ratio spreads (Ch.7) — open-ended risk / event risk; book: manage with iron fist",
  "Backspreads (Ch.8) — advanced, high-complexity / often unsuitable for seed capital",
  "Naked short straddles/strangles — undefined risk; use iron condor / iron butterfly instead",
] as const;

/**
 * Full Saliba chapter map as selector rules.
 * Complements NEWDUMP Saliba rules with collars, straddles, bear debit, range, and reject notes.
 */
export const SALIBA_RULES: StrategyRule[] = [
  {
    id: "saliba_ch1_covered_write",
    strategyId: "covered_call",
    name: "Saliba Ch.1 — Covered-Write (Managed Income)",
    thesis: "moderately_bullish",
    portfolioRole: "income_engine",
    riskProfile: "substantial_downside_capped_upside",
    approval: "level2_basic",
    ivConditions: ["elevated", "neutral"],
    trends: ["up", "sideways"],
    eventStance: "prefer_clear",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "Requires 100 shares per short call — neutral to mildly bullish only (Ch.1)",
      "Short-dated (≤45 DTE) near-money for income theta; deeper ITM / longer for more premium vs upside tradeoff",
      "Covered-write ≈ short-put risk profile — size and manage downside; never treat as free income",
      "Prefer steady/falling IV after entry (rising IV hurts short call)",
      "Plan adjustments (roll verticals / buy protection) before entry — not fire-and-forget",
    ],
    exitRules: ["profit_50pct_max", "dte_21_close_or_roll", "manual_review"],
    shortDeltaTarget: 0.3,
    dteMin: 14,
    dteMax: 45,
    priority: 0.82,
    growthPrimary: false,
    bookSource:
      "Saliba Option Spread Strategies (2009) Ch.1 Covered-Write — E:\\newdump distillation",
    structure: "Long stock + short call (buy-write)",
    notes: [
      "Seed accounts without shares: use bull put credit instead",
      "Book rejects late-night cash-machine marketing of covered writes",
    ],
  },
  {
    id: "saliba_ch2_bull_put_credit",
    strategyId: "bull_put_credit",
    name: "Saliba Ch.2 — Bull Put Credit Vertical",
    thesis: "moderately_bullish",
    portfolioRole: "income_engine",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["elevated", "neutral"],
    trends: ["up", "sideways"],
    eventStance: "avoid_earnings",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "Verticals for moderate directional move OR high-IV when naked long options are too rich (Ch.2)",
      "Bull put: short higher put + long lower put — max loss = width − credit before fill",
      "Support-bounce / mildly bullish income with hard floor",
      "Enter as multi-leg complex order — do not leg",
      "Short |delta| ~0.20–0.30; 21–45 DTE; liquid underlyings only",
      "Size to empire risk % of max loss, not credit size",
    ],
    exitRules: ["profit_50pct_max", "dte_21_close_or_roll", "stop_2x_credit", "friday_roll_or_close"],
    shortDeltaTarget: 0.25,
    dteMin: 21,
    dteMax: 45,
    priority: 0.93,
    growthPrimary: true,
    bookSource:
      "Saliba Option Spread Strategies (2009) Ch.2 Verticals — E:\\newdump distillation",
    structure: "Bull put credit vertical",
    notes: [
      "Synthetic twin of bull call debit for many purposes — pick by IV / debit preference",
      "Primary seed defined-risk engine when Level 3 available",
    ],
  },
  {
    id: "saliba_ch2_bear_call_credit",
    strategyId: "bear_call_credit",
    name: "Saliba Ch.2 — Bear Call Credit Vertical",
    thesis: "moderately_bearish",
    portfolioRole: "income_engine",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["elevated", "neutral"],
    trends: ["down", "sideways"],
    eventStance: "prefer_clear",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "Bear call credit for neutral-to-bearish / resistance rejection (Ch.2)",
      "Max profit = credit; max loss = width − credit",
      "Short call near technical resistance when IV supports selling premium",
      "Wing always on — never naked short call from this playbook",
      "Multi-leg execution; do not leave one side live after partial exit",
    ],
    exitRules: ["profit_50pct_max", "dte_21_close_or_roll", "stop_2x_credit"],
    shortDeltaTarget: 0.28,
    dteMin: 21,
    dteMax: 45,
    priority: 0.9,
    growthPrimary: true,
    bookSource:
      "Saliba Option Spread Strategies (2009) Ch.2 Verticals — E:\\newdump distillation",
    structure: "Bear call credit vertical",
    notes: ["Defined-risk short premium for mild bearish / range-top views"],
  },
  {
    id: "saliba_ch2_bull_call_debit",
    strategyId: "bull_call_debit",
    name: "Saliba Ch.2 — Bull Call Debit Vertical",
    thesis: "bullish",
    portfolioRole: "growth_tactical",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["low", "neutral"],
    trends: ["up"],
    eventStance: "prefer_clear",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "Bull call debit for moderate upside when long naked call is IV-rich (Ch.2)",
      "Max loss = net debit; BE ≈ long strike + debit",
      "Prefer limited-risk directional vs full stock purchase",
      "If IV elevated and debit expensive, prefer bull put credit instead",
    ],
    exitRules: ["profit_50pct_max", "stop_1x_debit", "dte_21_close_or_roll"],
    shortDeltaTarget: null,
    dteMin: 21,
    dteMax: 60,
    priority: 0.8,
    growthPrimary: false,
    bookSource:
      "Saliba Option Spread Strategies (2009) Ch.2 Verticals — E:\\newdump distillation",
    structure: "Bull call debit vertical",
    notes: ["Pair with NCI SuperBias BUY when available"],
  },
  {
    id: "saliba_ch2_bear_put_debit",
    strategyId: "bear_put_debit",
    name: "Saliba Ch.2 — Bear Put Debit Vertical",
    thesis: "bearish",
    portfolioRole: "growth_tactical",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["low", "neutral"],
    trends: ["down"],
    eventStance: "prefer_clear",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "Bear put debit for moderate downside (Ch.2 twin of bull call)",
      "Max loss = net debit; BE ≈ long put strike − debit",
      "Prefer when IV not punitive for debit structures",
      "Elevated IV: consider bear call credit instead for short-premium bearish view",
    ],
    exitRules: ["profit_50pct_max", "stop_1x_debit", "dte_21_close_or_roll"],
    shortDeltaTarget: null,
    dteMin: 21,
    dteMax: 60,
    priority: 0.79,
    growthPrimary: false,
    bookSource:
      "Saliba Option Spread Strategies (2009) Ch.2 Verticals — E:\\newdump distillation",
    structure: "Bear put debit vertical",
    notes: ["Defined-risk bearish alternative to naked long put"],
  },
  {
    id: "saliba_ch3_collar_hedge",
    strategyId: "long_put",
    name: "Saliba Ch.3 — Collar / Protective Floor (on Shares)",
    thesis: "moderately_bullish",
    portfolioRole: "hedge",
    riskProfile: "defined",
    approval: "level2_basic",
    ivConditions: ["elevated", "neutral", "low"],
    trends: ["up", "sideways", "down"],
    eventStance: "prefer_clear",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "Collar = long shares + short call + long put (Ch.3) — floor downside, cap upside",
      "Use when you must hold stock through uncertainty but want a hard loss limit",
      "Put strike = insurance floor; call strike finances put / sets sale target",
      "Reverse-collar is advanced inversion — not for seed income engines",
      "Multi-leg if available; know net debit/credit and max loss from put floor",
    ],
    exitRules: ["manual_review", "dte_21_close_or_roll", "profit_50pct_max"],
    shortDeltaTarget: 0.3,
    dteMin: 21,
    dteMax: 90,
    priority: 0.72,
    growthPrimary: false,
    bookSource:
      "Saliba Option Spread Strategies (2009) Ch.3 Collars — E:\\newdump distillation",
    structure: "Collar: long stock + short call + long put (put leg is the floor)",
    notes: [
      "Selector maps put-floor leg to long_put; combine with covered call process in journal",
      "Prefer over naked long stock into known risk windows",
    ],
  },
  {
    id: "saliba_ch4_long_straddle",
    strategyId: "long_straddle",
    name: "Saliba Ch.4 — Long Straddle (Large Move)",
    thesis: "large-move",
    portfolioRole: "growth_tactical",
    riskProfile: "defined",
    approval: "level2_basic",
    ivConditions: ["low", "neutral"],
    trends: ["up", "down", "sideways"],
    eventStance: "ok_through_events",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "Long ATM straddle when expecting a large move either way (Ch.4)",
      "Prefer cheaper IV entry — elevated IV inflates debit and needs bigger move",
      "Size small: full premium can expire worthless",
      "After binary events, plan for IV crush even if direction was correct",
      "Do not sell naked straddle/strangle for seed — use iron structures instead",
    ],
    exitRules: ["profit_50pct_max", "manual_review", "stop_1x_debit"],
    shortDeltaTarget: null,
    dteMin: 7,
    dteMax: 45,
    priority: 0.55,
    growthPrimary: false,
    bookSource:
      "Saliba Option Spread Strategies (2009) Ch.4 Straddles/Strangles — E:\\newdump distillation",
    structure: "Long ATM call + long ATM put",
    notes: ["Event risk both ways; not an income engine"],
  },
  {
    id: "saliba_ch4_long_strangle",
    strategyId: "long_strangle",
    name: "Saliba Ch.4 — Long Strangle (Cheaper Large Move)",
    thesis: "large-move",
    portfolioRole: "growth_tactical",
    riskProfile: "defined",
    approval: "level2_basic",
    ivConditions: ["low", "neutral"],
    trends: ["up", "down", "sideways"],
    eventStance: "ok_through_events",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "OTM put + OTM call — cheaper than straddle, needs larger move (Ch.4)",
      "Wider no-profit zone than straddle — size and horizon must match",
      "Prefer low/neutral IV; avoid paying peak IV into known events unless intentional",
    ],
    exitRules: ["profit_50pct_max", "manual_review", "stop_1x_debit"],
    shortDeltaTarget: null,
    dteMin: 14,
    dteMax: 60,
    priority: 0.52,
    growthPrimary: false,
    bookSource:
      "Saliba Option Spread Strategies (2009) Ch.4 Straddles/Strangles — E:\\newdump distillation",
    structure: "Long OTM put + long OTM call",
    notes: ["Liquidity and skew can differ between wings"],
  },
  {
    id: "saliba_ch5_iron_condor",
    strategyId: "iron_condor",
    name: "Saliba Ch.5 — Condor / Range Premium (Defined)",
    thesis: "range",
    portfolioRole: "income_engine",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["elevated", "neutral"],
    trends: ["sideways"],
    eventStance: "avoid_earnings",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "Directionless/range forecast required (Ch.5): support, resistance, mean-reversion",
      "Wings near S/R; short body near expected stay-zone (condor wider than butterfly)",
      "Forecast how long range lasts → choose DTE (time-in-range)",
      "Wings define max loss; credit defines max profit — show both with PoP",
      "Adjust when range migrates — do not hope through breakouts",
      "21–40 DTE preferred for theta + adjustability",
    ],
    exitRules: ["profit_50pct_max", "dte_21_close_or_roll", "stop_2x_credit"],
    shortDeltaTarget: 0.16,
    dteMin: 21,
    dteMax: 40,
    priority: 0.88,
    growthPrimary: false,
    bookSource:
      "Saliba Option Spread Strategies (2009) Ch.5 Butterflies/Condors — E:\\newdump distillation",
    structure: "Iron condor (defined-risk short strangle with wings)",
    notes: [
      "Empire seed: prefer iron condor over naked short strangle",
      "Butterfly is tighter range / higher sensitivity to pin",
    ],
  },
  {
    id: "saliba_ch5_iron_butterfly",
    strategyId: "iron_butterfly",
    name: "Saliba Ch.5 — Iron Butterfly (Tight Range)",
    thesis: "range",
    portfolioRole: "income_engine",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["elevated", "neutral"],
    trends: ["sideways"],
    eventStance: "avoid_earnings",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "Sell ATM straddle + buy protective wings — narrow profit zone (Ch.5)",
      "Use when strong mean-reversion to a single price area is expected",
      "Higher credit than condor but tighter management; pin risk at center",
      "Elevated IV entry helps short body; wings still define max loss",
    ],
    exitRules: ["profit_50pct_max", "dte_21_close_or_roll", "stop_2x_credit"],
    shortDeltaTarget: 0.5,
    dteMin: 14,
    dteMax: 35,
    priority: 0.74,
    growthPrimary: false,
    bookSource:
      "Saliba Option Spread Strategies (2009) Ch.5 Butterflies/Condors — E:\\newdump distillation",
    structure: "Iron butterfly",
    notes: ["Prefer only when range forecast is tight and liquid"],
  },
  {
    id: "saliba_ch6_calendar_diagonal",
    strategyId: "money_press_put_diagonal",
    name: "Saliba Ch.6 — Calendar / Time Spread Discipline",
    thesis: "bullish",
    portfolioRole: "income_engine",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["elevated", "neutral"],
    trends: ["up", "sideways"],
    eventStance: "prefer_clear",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "Time-spread logic (Ch.6): term structure of IV matters",
      "Avoid long calendar when front IV is depressed vs back against your forecast",
      "Prefer structures where short front premium is rich relative to back (aligns with weekly press)",
      "Enter multi-leg; liquid underlyings only",
      "Manage rolls as time and spot move — not fire-and-forget",
    ],
    exitRules: ["friday_roll_or_close", "dte_7_close_or_roll", "manual_review", "profit_50pct_max"],
    shortDeltaTarget: 0.5,
    dteMin: 3,
    dteMax: 10,
    priority: 0.89,
    growthPrimary: true,
    bookSource:
      "Saliba Option Spread Strategies (2009) Ch.6 Calendars + Money Press — E:\\newdump distillation",
    structure: "Put diagonal / calendar family with term-structure check",
    notes: [
      "Maps to empire money_press_put_diagonal rather than pure same-strike calendar",
      "Call vs put time spreads often synthetic — pricing/liquidity chooses",
    ],
  },
];

/** UI helper: pick regime row for SuperBias / trend */
export function salibaRegimesForTrend(
  trend: "up" | "down" | "sideways" | "unknown" | string,
): (typeof SALIBA_REGIME_MATRIX)[number] | undefined {
  if (trend === "up") return SALIBA_REGIME_MATRIX[0];
  if (trend === "down") return SALIBA_REGIME_MATRIX[1];
  if (trend === "sideways") return SALIBA_REGIME_MATRIX[2];
  return undefined;
}
