/**
 * Structured strategy rule library — the "option book" gate for Phase 4.
 * Rules are deterministic; selector only scores what matches MarketContext.
 */

import type { StrategyRule } from "./types";
import { BOOK_EXTRA_RULES } from "./bookRulesExtra";
import { BOOK_INGEST_RULES } from "./bookIngestRules";

const CORE_STRATEGY_RULES: StrategyRule[] = [
  {
    id: "wheel_csp_entry",
    strategyId: "cash_secured_put",
    name: "Wheel — Cash-Secured Put Entry",
    thesis: "moderately_bullish",
    portfolioRole: "income_engine",
    riskProfile: "substantial_downside_capped_upside",
    approval: "level2_basic",
    ivConditions: ["elevated", "neutral"],
    trends: ["up", "sideways"],
    eventStance: "avoid_earnings",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "IV rank elevated or neutral (prefer elevated to sell premium)",
      "30–45 DTE preferred",
      "Short put |delta| ~0.25",
      "Cash reserved = strike × 100 × contracts − credit",
      "Underlying in wheel universe or user-approved quality name",
    ],
    exitRules: ["profit_50pct_max", "dte_21_close_or_roll", "assignment_then_cc"],
    shortDeltaTarget: 0.25,
    dteMin: 21,
    dteMax: 45,
    priority: 0.95,
    growthPrimary: true,
    bookSource: "NCI Build Spec Strategy 1 (Wheel) + OptionScope book_pdf:34-45",
    structure: "Sell cash-secured put; reserve cash for assignment",
    notes: [
      "Primary income engine for account growth on Robinhood Level 2+",
      "On assignment, campaign continues as covered call",
    ],
  },
  {
    id: "wheel_cc_income",
    strategyId: "covered_call",
    name: "Wheel — Covered Call on Shares",
    thesis: "neutral",
    portfolioRole: "campaign",
    riskProfile: "substantial_downside_capped_upside",
    approval: "level2_basic",
    ivConditions: ["elevated", "neutral"],
    trends: ["up", "sideways", "down"],
    eventStance: "avoid_ex_div",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "Own 100 shares per contract",
      "Sell call |delta| ~0.30",
      "30–45 DTE preferred",
      "Avoid deep ITM calls into ex-dividend when early assignment risk is high",
    ],
    exitRules: ["profit_50pct_max", "dte_21_close_or_roll", "manual_review"],
    shortDeltaTarget: 0.30,
    dteMin: 21,
    dteMax: 45,
    priority: 0.9,
    growthPrimary: true,
    bookSource: "NCI Build Spec Strategy 1 (Wheel) + OptionScope book_pdf:17-22",
    structure: "Long stock + short call",
    notes: ["Second leg of wheel after CSP assignment", "Premium is a cushion, not full downside protection"],
  },
  {
    id: "bull_put_credit_income",
    strategyId: "bull_put_credit",
    name: "Bull Put Credit Spread",
    thesis: "moderately_bullish",
    portfolioRole: "income_engine",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["elevated", "neutral"],
    trends: ["up", "sideways"],
    eventStance: "avoid_earnings",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "IV elevated preferred (sell premium)",
      "30–45 DTE",
      "Short put delta ~0.30",
      "Defined risk = width − credit",
    ],
    exitRules: ["profit_50pct_max", "dte_21_close_or_roll", "stop_2x_credit"],
    shortDeltaTarget: 0.30,
    dteMin: 21,
    dteMax: 45,
    priority: 0.88,
    growthPrimary: true,
    bookSource: "OptionScope book_pdf:61-66 + ROADMAP sample rule",
    structure: "Short higher put + long lower put, same expiry",
    notes: ["Capital-efficient alternative to CSP when Level 3 is available"],
  },
  {
    id: "bear_call_credit_income",
    strategyId: "bear_call_credit",
    name: "Bear Call Credit Spread",
    thesis: "moderately_bearish",
    portfolioRole: "income_engine",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["elevated", "neutral"],
    trends: ["down", "sideways"],
    eventStance: "avoid_earnings",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: ["IV elevated preferred", "30–45 DTE", "Short call delta ~0.30"],
    exitRules: ["profit_50pct_max", "dte_21_close_or_roll", "stop_2x_credit"],
    shortDeltaTarget: 0.30,
    dteMin: 21,
    dteMax: 45,
    priority: 0.85,
    growthPrimary: true,
    bookSource: "OptionScope book_pdf:53-61",
    structure: "Short lower call + long higher call, same expiry",
    notes: [],
  },
  {
    id: "iron_condor_range",
    strategyId: "iron_condor",
    name: "Iron Condor Range Income",
    thesis: "range",
    portfolioRole: "income_engine",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["elevated"],
    trends: ["sideways"],
    eventStance: "avoid_earnings",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: ["Elevated IV only", "Range-bound spot trend", "Wings define max loss", "Target 30–45 DTE"],
    exitRules: ["profit_50pct_max", "dte_21_close_or_roll", "stop_2x_credit"],
    shortDeltaTarget: 0.16,
    dteMin: 25,
    dteMax: 45,
    priority: 0.8,
    growthPrimary: false,
    bookSource: "OptionScope book_pdf:66-69",
    structure: "Short put spread + short call spread",
    notes: ["Show PoP and expected value together"],
  },
  {
    id: "bull_call_debit_growth",
    strategyId: "bull_call_debit",
    name: "Bull Call Debit Spread (Tactical Growth)",
    thesis: "bullish",
    portfolioRole: "growth_tactical",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["low", "neutral"],
    trends: ["up"],
    eventStance: "prefer_clear",
    minLiquidity: "normal",
    newsBias: "positive",
    entryRules: ["Prefer lower IV when buying premium", "Uptrend confirmed", "Defined debit risk only"],
    exitRules: ["profit_50pct_max", "stop_1x_debit", "manual_review"],
    shortDeltaTarget: null,
    dteMin: 21,
    dteMax: 60,
    priority: 0.7,
    growthPrimary: false,
    bookSource: "OptionScope book_pdf:53-61",
    structure: "Long lower call + short higher call",
    notes: ["Use sparingly — account growth primary path is premium selling / wheel"],
  },
  {
    id: "bear_put_debit_growth",
    strategyId: "bear_put_debit",
    name: "Bear Put Debit Spread (Tactical Hedge/Growth)",
    thesis: "bearish",
    portfolioRole: "growth_tactical",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["low", "neutral"],
    trends: ["down"],
    eventStance: "prefer_clear",
    minLiquidity: "normal",
    newsBias: "negative",
    entryRules: ["Prefer lower IV when buying premium", "Downtrend confirmed"],
    exitRules: ["profit_50pct_max", "stop_1x_debit", "manual_review"],
    shortDeltaTarget: null,
    dteMin: 21,
    dteMax: 60,
    priority: 0.65,
    growthPrimary: false,
    bookSource: "OptionScope book_pdf:61-66",
    structure: "Long higher put + short lower put",
    notes: [],
  },
  {
    id: "long_call_basic",
    strategyId: "long_call",
    name: "Long Call (Basic Directional)",
    thesis: "bullish",
    portfolioRole: "growth_tactical",
    riskProfile: "defined",
    approval: "level2_basic",
    ivConditions: ["low"],
    trends: ["up"],
    eventStance: "prefer_clear",
    minLiquidity: "normal",
    newsBias: "positive",
    entryRules: ["Low IV preferred", "Risk limited to debit", "Size small — full premium can be lost"],
    exitRules: ["profit_50pct_max", "stop_1x_debit", "manual_review"],
    shortDeltaTarget: null,
    dteMin: 30,
    dteMax: 90,
    priority: 0.45,
    growthPrimary: false,
    bookSource: "OptionScope book_pdf:pre-covered-call",
    structure: "Long call",
    notes: ["Not the primary growth engine"],
  },
  {
    id: "long_put_hedge",
    strategyId: "long_put",
    name: "Long Put (Hedge / Bearish)",
    thesis: "bearish",
    portfolioRole: "hedge",
    riskProfile: "defined",
    approval: "level2_basic",
    ivConditions: ["low", "neutral"],
    trends: ["down"],
    eventStance: "ok_through_events",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: ["Risk limited to debit", "May be used as portfolio hedge"],
    exitRules: ["manual_review", "profit_50pct_max"],
    shortDeltaTarget: null,
    dteMin: 21,
    dteMax: 90,
    priority: 0.4,
    growthPrimary: false,
    bookSource: "OptionScope book_pdf:27-34",
    structure: "Long put",
    notes: [],
  },
  {
    id: "long_straddle_event",
    strategyId: "long_straddle",
    name: "Long Straddle (Large Move)",
    thesis: "large-move",
    portfolioRole: "growth_tactical",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["low"],
    trends: ["sideways"],
    eventStance: "ok_through_events",
    minLiquidity: "tight",
    newsBias: "any",
    entryRules: ["Low IV before expected large move", "High debit cost — size small"],
    exitRules: ["manual_review", "profit_50pct_max"],
    shortDeltaTarget: null,
    dteMin: 7,
    dteMax: 45,
    priority: 0.35,
    growthPrimary: false,
    bookSource: "OptionScope book_pdf:50-52",
    structure: "Long ATM call + long ATM put",
    notes: ["IV crush risk after events"],
  },
];

/** Core + hand book rules + PDF-ingest seeds (dedupe by id). */
export const STRATEGY_RULES: StrategyRule[] = (() => {
  const map = new Map<string, StrategyRule>();
  for (const r of [...CORE_STRATEGY_RULES, ...BOOK_EXTRA_RULES, ...BOOK_INGEST_RULES]) {
    map.set(r.id, r);
  }
  return [...map.values()];
})();

export function getRuleById(id: string): StrategyRule | undefined {
  return STRATEGY_RULES.find((r) => r.id === id);
}

export function getRulesByStrategyId(strategyId: string): StrategyRule[] {
  return STRATEGY_RULES.filter((r) => r.strategyId === strategyId);
}

export function growthPrimaryRules(): StrategyRule[] {
  return STRATEGY_RULES.filter((r) => r.growthPrimary);
}
