/**
 * Structured strategy rule library — the "option book" gate for Phase 4.
 * Rules are deterministic; selector only scores what matches MarketContext.
 */

import type { StrategyRule } from "./types";
import { BOOK_EXTRA_RULES } from "./bookRulesExtra";
import { BOOK_INGEST_RULES } from "./bookIngestRules";
import { NEWDUMP_RULES } from "./newdumpRules";
import { BOOKLIBRARY_RULES } from "./bookLibraryRules";
import { DUMP2_RULES } from "./dump2Rules";
import { DUMP3_RULES } from "./dump3Rules";
import { SALIBA_RULES } from "./salibaPlaybook";

const CORE_STRATEGY_RULES: StrategyRule[] = [
  {
    id: "wheel_csp_entry",
    strategyId: "cash_secured_put",
    name: "Wheel — Cash-Secured Put Entry",
    thesis: "moderately_bullish",
    portfolioRole: "income_engine",
    riskProfile: "substantial_downside_capped_upside",
    approval: "level2_basic",
    ivConditions: ["elevated", "neutral"],
    trends: ["up", "sideways"],
    eventStance: "avoid_earnings",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "IV rank elevated or neutral (prefer elevated to sell premium)",
      "30–45 DTE preferred",
      "Short put |delta| ~0.20–0.30 (Steadiest ideal band; avoid >0.40 assignment coin-flip)",
      "Cash reserved = strike × 100 × contracts − credit",
      "Only names you would not mind owning; prefer quality / strong FCF yield large-caps",
      "Avoid earnings inside short DTE",
    ],
    exitRules: ["profit_50pct_max", "dte_21_close_or_roll", "assignment_then_cc"],
    shortDeltaTarget: 0.25,
    dteMin: 21,
    dteMax: 45,
    priority: 0.95,
    growthPrimary: true,
    bookSource:
      "NCI Wheel + Henry Moldavskiy The Steadiest Option Trader 2023 Ch.8–9 (personal reference)",
    structure: "Sell cash-secured put; reserve cash for assignment",
    notes: [
      "Primary income engine for account growth on Robinhood Level 2+ when cash allows",
      "On assignment, campaign continues as covered call",
      "Seed accounts usually cannot cash-secure — use defined credit spreads / Money Press instead",
    ],
  },
  {
    id: "wheel_cc_income",
    strategyId: "covered_call",
    name: "Wheel — Covered Call on Shares",
    thesis: "neutral",
    portfolioRole: "campaign",
    riskProfile: "substantial_downside_capped_upside",
    approval: "level2_basic",
    ivConditions: ["elevated", "neutral"],
    trends: ["up", "sideways", "down"],
    eventStance: "avoid_ex_div",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "Own 100 shares per contract",
      "Sell call |delta| ~0.30",
      "30–45 DTE preferred",
      "Avoid deep ITM calls into ex-dividend when early assignment risk is high",
    ],
    exitRules: ["profit_50pct_max", "dte_21_close_or_roll", "manual_review"],
    shortDeltaTarget: 0.30,
    dteMin: 21,
    dteMax: 45,
    priority: 0.9,
    growthPrimary: true,
    bookSource: "NCI Build Spec Strategy 1 (Wheel) + OptionScope book_pdf:17-22",
    structure: "Long stock + short call",
    notes: ["Second leg of wheel after CSP assignment", "Premium is a cushion, not full downside protection"],
  },
  {
    id: "bull_put_credit_income",
    strategyId: "bull_put_credit",
    name: "Bull Put Credit Spread",
    thesis: "moderately_bullish",
    portfolioRole: "income_engine",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["elevated", "neutral"],
    trends: ["up", "sideways"],
    eventStance: "avoid_earnings",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "IV elevated preferred (sell premium)",
      "30–45 DTE",
      "Short put delta ~0.30",
      "Defined risk = width − credit",
      "Close Friday morning if between strikes near expiry (pin risk)",
    ],
    exitRules: ["profit_50pct_max", "dte_21_close_or_roll", "stop_2x_credit", "friday_roll_or_close"],
    shortDeltaTarget: 0.30,
    dteMin: 21,
    dteMax: 45,
    priority: 0.88,
    growthPrimary: true,
    bookSource:
      "OptionScope + Henry Moldavskiy The Steadiest Option Trader 2023 Ch.12 (personal reference)",
    structure: "Short higher put + long lower put, same expiry",
    notes: ["Capital-efficient alternative to CSP when Level 3 is available"],
  },
  {
    id: "bear_call_credit_income",
    strategyId: "bear_call_credit",
    name: "Bear Call Credit Spread",
    thesis: "moderately_bearish",
    portfolioRole: "income_engine",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["elevated", "neutral"],
    trends: ["down", "sideways"],
    eventStance: "avoid_earnings",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "IV elevated preferred",
      "30–45 DTE",
      "Short call delta ~0.30",
      "Prefer short strike near resistance / consolidation high / overbought fade",
      "Max profit = credit; max loss = width − credit",
    ],
    exitRules: ["profit_50pct_max", "dte_21_close_or_roll", "stop_2x_credit", "friday_roll_or_close"],
    shortDeltaTarget: 0.30,
    dteMin: 21,
    dteMax: 45,
    priority: 0.85,
    growthPrimary: true,
    bookSource:
      "OptionScope + Henry Moldavskiy The Steadiest Option Trader 2023 Ch.11 (personal reference)",
    structure: "Short lower call + long higher call, same expiry",
    notes: ["Neutral-to-bearish income with defined risk"],
  },
  {
    id: "iron_condor_range",
    strategyId: "iron_condor",
    name: "Iron Condor Range Income",
    thesis: "range",
    portfolioRole: "income_engine",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["elevated"],
    trends: ["sideways"],
    eventStance: "avoid_earnings",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "Elevated IV only",
      "Range-bound spot trend",
      "Wings define max loss",
      "Target 21–40 DTE (faster theta; manage wings actively)",
      "Roll/close if price approaches short strikes — do not hold hope through breakouts",
    ],
    exitRules: ["profit_50pct_max", "dte_21_close_or_roll", "stop_2x_credit"],
    shortDeltaTarget: 0.16,
    dteMin: 21,
    dteMax: 40,
    priority: 0.8,
    growthPrimary: false,
    bookSource:
      "OptionScope + Henry Moldavskiy The Steadiest Option Trader 2023 Ch.13 (personal reference)",
    structure: "Short put spread + short call spread",
    notes: ["Show PoP and expected value together"],
  },
  {
    id: "money_press_put_diagonal_income",
    strategyId: "money_press_put_diagonal",
    name: "Money Press — Put Diagonal (Weekly Premium)",
    thesis: "bullish",
    portfolioRole: "income_engine",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["elevated", "neutral"],
    trends: ["sideways", "up"],
    eventStance: "prefer_clear",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: [
      "Money Press (book): SELL weekly put ATM/near-money (higher strike) + BUY lower-strike put 3–6 months out (protection)",
      "Short strike ALWAYS higher than protection strike — this is a diagonal, not a same-strike calendar",
      "Enter both legs together; usually net debit at open; use limit orders on the diagonal",
      "Protection cost ≈ 2.5× ATM weekly premium (cheat sheet); risk capital ≈ strike width",
      "Prefer liquid large/triple-digit names with weeklies; do NOT start if earnings < 2 weeks away",
      "Require a compelling circumstance (earnings reaction, crow-bar, product launch, etc.) + price/volume confirm",
      "Avoid commodities, most ETFs, clothing retailers, semis for this method",
      "Flat-to-up underlying; Friday roll short; keep protection ≥ ~6 weeks DTE",
    ],
    exitRules: ["friday_roll_or_close", "dte_7_close_or_roll", "manual_review", "profit_50pct_max"],
    shortDeltaTarget: 0.5,
    dteMin: 3,
    dteMax: 10,
    priority: 0.9,
    growthPrimary: true,
    bookSource:
      "Preston James — The Money Press Method 2020 (personal reference): diagonal put = weekly short higher + long lower 3–6 mo",
    structure: "Short near put (higher/ATM) + long far put (lower, 3–6 mo) — diagonal",
    notes: [
      "Primary empire income path when CSP cash lock is too large",
      "WORK-style example shape: short ~ATM weekly, long ~10–15% lower / multi-month",
      "Friday = roll/adjust day (~20–30 min). Multi-week press — do not judge on a single week",
      "Marketing claims in the book are not guarantees; size under empire risk budget",
    ],
  },
  {
    id: "bull_call_debit_growth",
    strategyId: "bull_call_debit",
    name: "Bull Call Debit Spread (Tactical Growth)",
    thesis: "bullish",
    portfolioRole: "growth_tactical",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["low", "neutral"],
    trends: ["up"],
    eventStance: "prefer_clear",
    minLiquidity: "normal",
    newsBias: "positive",
    entryRules: ["Prefer lower IV when buying premium", "Uptrend confirmed", "Defined debit risk only"],
    exitRules: ["profit_50pct_max", "stop_1x_debit", "manual_review"],
    shortDeltaTarget: null,
    dteMin: 21,
    dteMax: 60,
    priority: 0.7,
    growthPrimary: false,
    bookSource: "OptionScope book_pdf:53-61",
    structure: "Long lower call + short higher call",
    notes: ["Use sparingly — account growth primary path is premium selling / wheel"],
  },
  {
    id: "bear_put_debit_growth",
    strategyId: "bear_put_debit",
    name: "Bear Put Debit Spread (Tactical Hedge/Growth)",
    thesis: "bearish",
    portfolioRole: "growth_tactical",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["low", "neutral"],
    trends: ["down"],
    eventStance: "prefer_clear",
    minLiquidity: "normal",
    newsBias: "negative",
    entryRules: ["Prefer lower IV when buying premium", "Downtrend confirmed"],
    exitRules: ["profit_50pct_max", "stop_1x_debit", "manual_review"],
    shortDeltaTarget: null,
    dteMin: 21,
    dteMax: 60,
    priority: 0.65,
    growthPrimary: false,
    bookSource: "OptionScope book_pdf:61-66",
    structure: "Long higher put + short lower put",
    notes: [],
  },
  {
    id: "long_call_basic",
    strategyId: "long_call",
    name: "Long Call (Basic Directional)",
    thesis: "bullish",
    portfolioRole: "growth_tactical",
    riskProfile: "defined",
    approval: "level2_basic",
    ivConditions: ["low"],
    trends: ["up"],
    eventStance: "prefer_clear",
    minLiquidity: "normal",
    newsBias: "positive",
    entryRules: ["Low IV preferred", "Risk limited to debit", "Size small — full premium can be lost"],
    exitRules: ["profit_50pct_max", "stop_1x_debit", "manual_review"],
    shortDeltaTarget: null,
    dteMin: 30,
    dteMax: 90,
    priority: 0.45,
    growthPrimary: false,
    bookSource: "OptionScope book_pdf:pre-covered-call",
    structure: "Long call",
    notes: ["Not the primary growth engine"],
  },
  {
    id: "long_put_hedge",
    strategyId: "long_put",
    name: "Long Put (Hedge / Bearish)",
    thesis: "bearish",
    portfolioRole: "hedge",
    riskProfile: "defined",
    approval: "level2_basic",
    ivConditions: ["low", "neutral"],
    trends: ["down"],
    eventStance: "ok_through_events",
    minLiquidity: "normal",
    newsBias: "any",
    entryRules: ["Risk limited to debit", "May be used as portfolio hedge"],
    exitRules: ["manual_review", "profit_50pct_max"],
    shortDeltaTarget: null,
    dteMin: 21,
    dteMax: 90,
    priority: 0.4,
    growthPrimary: false,
    bookSource: "OptionScope book_pdf:27-34",
    structure: "Long put",
    notes: [],
  },
  {
    id: "long_straddle_event",
    strategyId: "long_straddle",
    name: "Long Straddle (Large Move)",
    thesis: "large-move",
    portfolioRole: "growth_tactical",
    riskProfile: "defined",
    approval: "level3_spreads",
    ivConditions: ["low"],
    trends: ["sideways"],
    eventStance: "ok_through_events",
    minLiquidity: "tight",
    newsBias: "any",
    entryRules: ["Low IV before expected large move", "High debit cost — size small"],
    exitRules: ["manual_review", "profit_50pct_max"],
    shortDeltaTarget: null,
    dteMin: 7,
    dteMax: 45,
    priority: 0.35,
    growthPrimary: false,
    bookSource: "OptionScope book_pdf:50-52",
    structure: "Long ATM call + long ATM put",
    notes: ["IV crush risk after events"],
  },
];

/** Core + hand books + L/E:\newdump distillations + Saliba playbook + PDF-ingest seeds (dedupe by id). */
export const STRATEGY_RULES: StrategyRule[] = (() => {
  const map = new Map<string, StrategyRule>();
  for (const r of [
    ...CORE_STRATEGY_RULES,
    ...BOOK_EXTRA_RULES,
    ...NEWDUMP_RULES,
    ...SALIBA_RULES,
    ...BOOKLIBRARY_RULES,
    ...DUMP2_RULES,
    ...DUMP3_RULES,
    ...BOOK_INGEST_RULES,
  ]) {
    map.set(r.id, r);
  }
  return [...map.values()];
})();

export function getRuleById(id: string): StrategyRule | undefined {
  return STRATEGY_RULES.find((r) => r.id === id);
}

export function getRulesByStrategyId(strategyId: string): StrategyRule[] {
  return STRATEGY_RULES.filter((r) => r.strategyId === strategyId);
}

export function growthPrimaryRules(): StrategyRule[] {
  return STRATEGY_RULES.filter((r) => r.growthPrimary);
}
